### ISSUE TITLE
Supporting Linux 6.10

### ISSUE THREAD

**Issue by keryell** [amd/xdna-driver#128]
Independently from this driver, I am still have a lot of issues with my HP ZBook Power 15.6 inch G10 A to have basic power control to work correctly so I am trying all the latest Linux versions.
So, as I explained recently to @sonals, if I want to use also XDNA, it would be nice to have XRT & XDNA to track the latest development.

**Comment by mamin506** [comment]
@keryell , I tried compile xdna driver with 6.10.0-rc2, see PR #111. One of my development machine has 6.10 kernel with ubuntu 22.04. Not sure if you encounter any issue with your 6.10 build?  

BTW, the IOMMU SVA patch is fully merged. So I'm compile linux kernel from upstream.

**Comment by keryell** [comment]
Great! I missed this PR as I have been distracted by another project.
I need to try it.
Thanks.

**Comment by xmixahlx** [comment]
I encounter an error when building the dkms module of xrt, but the xrt package, xrt-xdna package, and xrt-xdna dkms build OK:
```
$ xrt-smi examine
System Configuration
  OS Name              : Linux
  Release              : 6.10.0-rc4-zen4-xmixahlx12
  Version              : #1 SMP PREEMPT_DYNAMIC Thu Jun 20 14:54:35 PDT 2024
  Machine              : x86_64
  CPU Cores            : 16
  Memory               : 55940 MB
  Distribution         : Debian GNU/Linux trixie/sid
  GLIBC                : 2.38
  Model                : 21K9001NUS
  BIOS vendor          : LENOVO
  BIOS version         : R2FET55W (1.35 )

XRT
  Version              : 2.18.0
  Branch               : HEAD
  Hash                 : fdba05d985fc9a083af6dee1a18688e6f9796f5a
  Hash Date            : 2024-06-20 17:32:52
  xocl                 : unknown, unknown
  xclmgmt              : unknown, unknown
WARNING: xclmgmt version is unknown. Is xclmgmt driver loaded? Or is MSD/MPD running?
  amdxdna              : 2.18.0_20240620, d973fbc6826f6dca82ff4ae7d76b414d2ac88667
  NPU Firmware Version : N/A

Devices present
|BDF             ||Name          |
|----------------||--------------|
|[0000:65:00.1]  ||RyzenAI-npu1  |
``````

$ more /var/lib/dkms/xrt/2.18.0/build/make.log
DKMS make.log for xrt-2.18.0 for kernel 6.10.0-rc4-zen4-xmixahlx12 (x86_64)
Thu Jun 20 17:40:01 PDT 2024
cd userpf; make all
make[1]: Entering directory '/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf'
/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf
make -C /lib/modules/6.10.0-rc4-zen4-xmixahlx12/build M=/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf
modules
make[2]: Entering directory '/usr/src/linux-headers-6.10.0-rc4-zen4-xmixahlx12'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc-13 (Debian 13.3.0-1) 13.3.0
  You are using:           gcc (Debian 13.3.0-1) 13.3.0
  CC [M]  /var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_subdev.o
In file included from /var/lib/dkms/xrt/2.18.0/build/driver/xocl//../include/kds_client.h:23,
                 from /var/lib/dkms/xrt/2.18.0/build/driver/xocl//../include/kds_core.h:24,
                 from /var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_drv.h:60,
                 from /var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_subdev.c:20:
/var/lib/dkms/xrt/2.18.0/build/driver/xocl//../include/xrt_cu.h:416:1: warning: 'inline' is not at beginni
ng of declaration [-Wold-style-declaration]
  416 | static void inline xrt_cu_enable_intr(struct xrt_cu *xcu, u32 intr_type)
      | ^~~~~~
/var/lib/dkms/xrt/2.18.0/build/driver/xocl//../include/xrt_cu.h:422:1: warning: 'inline' is not at beginni
ng of declaration [-Wold-style-declaration]
  422 | static void inline xrt_cu_disable_intr(struct xrt_cu *xcu, u32 intr_type)
      | ^~~~~~
/var/lib/dkms/xrt/2.18.0/build/driver/xocl//../include/xrt_cu.h:428:1: warning: 'inline' is not at beginni
ng of declaration [-Wold-style-declaration]
  428 | static u32 inline xrt_cu_clear_intr(struct xrt_cu *xcu)
      | ^~~~~~
/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_drv.h: In function 'xocl_subdev_priv_alloc':
/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_drv.h:462:16: error: implicit declaration of fun
ction 'vzalloc'; did you mean 'kvzalloc'? [-Werror=implicit-function-declaration]
  462 |         priv = vzalloc(sizeof(*priv) + size);
      |                ^~~~~~~
      |                kvzalloc
/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_drv.h:462:14: warning: assignment to 'struct xoc
l_subdev_priv *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  462 |         priv = vzalloc(sizeof(*priv) + size);
      |              ^
/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_subdev.c: In function 'xocl_subdev_get_info':
/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_subdev.c:255:21: warning: assignment to 'struct
xocl_subdev_info *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  255 |         subdev_info = vzalloc(sizeof(*subdev_info) *
      |                     ^
/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_subdev.c:272:17: error: implicit declaration of
function 'vfree'; did you mean 'kvfree'? [-Werror=implicit-function-declaration]
  272 |                 vfree(subdev_info);
      |                 ^~~~~
      |                 kvfree
/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_subdev.c: In function '__xocl_subdev_construct':
/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_subdev.c:463:21: warning: assignment to 'struct
resource *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  463 |                 res = vzalloc(sizeof (*res) * subdev->info.num_res);
      |                     ^
/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_subdev.c:537:27: warning: assignment to 'struct
xocl_subdev_priv *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
  537 |                 priv_data = vzalloc(subdev->info.data_len + sizeof(*priv_data));
      |                           ^
/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_subdev.c: In function 'xocl_request_firmware':
/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_subdev.c:2208:16: error: implicit declaration of
 function 'vmalloc'; did you mean 'kvmalloc'? [-Werror=implicit-function-declaration]
 2208 |         *buf = vmalloc(fw->size);
      |                ^~~~~~~
      |                kvmalloc
/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_subdev.c:2208:14: warning: assignment to 'char *
' from 'int' makes pointer from integer without a cast [-Wint-conversion]
 2208 |         *buf = vmalloc(fw->size);
      |              ^
cc1: some warnings being treated as errors
make[4]: *** [scripts/Makefile.build:244: /var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf/../xocl_subdev
.o] Error 1
make[3]: *** [/usr/src/linux-headers-6.10.0-rc4-zen4-xmixahlx12/Makefile:1934: /var/lib/dkms/xrt/2.18.0/bu
ild/driver/xocl/userpf] Error 2
make[2]: *** [Makefile:240: __sub-make] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-6.10.0-rc4-zen4-xmixahlx12'
make[1]: *** [Makefile:137: all] Error 2
make[1]: Leaving directory '/var/lib/dkms/xrt/2.18.0/build/driver/xocl/userpf'
make: *** [Makefile:2: all] Error 2
```

**Comment by maxzhen** [comment]
This error can be ignored safely.

**Comment by xmixahlx** [comment]
Ignored? The build error results in the xrt dkms kernel modules failing to build. Building against patched 6.8.12 is successful.

**Comment by maxzhen** [comment]
The xocl driver and xclmgmt driver are not relevant here.

**Comment by xmixahlx** [comment]
Interesting. I would recommend clarifying that in the installation description.

Building the debian package of xrt prepares the dkms for xocl and xclmgmt. The build failure will throw errors for these modules until it is resolved.

The circumstance of the build being successful on 6.8.12 and unsuccessful on 6.10-rc4 seems to indicate a separate issue.

**Comment by maxzhen** [comment]
The xocl and xclmgmt driver code has not sync'ed up with 6.10 yet. They will be fixed later soon. But, we don't really care for NPU support.

**Comment by xmixahlx** [comment]
OK.

It may not be a responsibility here, but the solution seems to be:
* Document the lack of need of xocl and xclmgmt drivers for xdna.
* Separate the dkms component of the xrt package.
 
Until the dkms component is separated, the broken xrt package will constantly attempt to build the (unneeded) kernel drivers. Any configuration you would process for the dkms after install will need to be re-applied after each xrt package update. An intervention/patch of the dkms config prior to build is the quick fix.

**Comment by sonals** [comment]
I believe we support _-noalveo_ switch when building XRT. Can you try that?

**Comment by maxzhen** [comment]
Updated build instruction. Please run "./build.sh -noert -noalveo" to build XRT.

**Comment by xmixahlx** [comment]
Confirming that -noalveo works for me to exclude the dkms component. Thank you for clarifying!
