### ISSUE TITLE
Upstream

### ISSUE THREAD

**Issue by IgorTorrente-col** [amd/xdna-driver#160]
Now the we have the IOMMU SVA support [upstreamed](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=a5a91e54846d35c234939fb9170e035805353049), do you have intentions to upstream the xdna-driver?

**Comment by maxzhen** [comment]
Yes, we are working on the upstream patch set.

**Comment by IgorTorrente-col** [comment]
Cool, thank you for the answer!
