### ISSUE TITLE
Is there a way I can train model both with NPU and GPU at the same time?

### ISSUE THREAD

**Issue by themoneyevo** [amd/xdna-driver#19]
Since AMD 7845hs and AMD 8845hs product page says they are very powerful. The 8845hs  has "Total Processor Performance :  38 TOPS". I want use the power of the chip, is there a way I can train my model using NPU and GPU at the same time to leverage the full power of the chip.

**Comment by andyluo7** [comment]
@themoneyevo , you can run one model on NPU and the other on GPU.

**Comment by themoneyevo** [comment]
now, how can i  train model with npu ?

**Comment by andyluo7** [comment]
@themoneyevo, npu is for inference only but for model training. You should use GPU or CPU to train models.
