### ISSUE TITLE
Update xdna-driver and XRT version to succeed compiling with real 6.8

### ISSUE THREAD

**Issue by keryell** [amd/xdna-driver#31]
The XRT required in the git submodule is too old to compile with 6.8 but at the same time this driver does not compile with XRT of the day.

**Comment by maxzhen** [comment]
We'll update XRT git submodule later. For now, the compilation failure of the XRT driver can be ignored.

**Comment by keryell** [comment]
The situation is complicated at least, since there are a few bugs in XRT currently. :-(
Need to wait for https://github.com/Xilinx/XRT/pull/8046 to land.

**Comment by keryell** [comment]
I have added an easy one to avoid breaking systems with pre-6.8 kernels https://github.com/amd/xdna-driver/pull/32

**Comment by keryell** [comment]
Done by https://github.com/amd/xdna-driver/pull/34 and https://github.com/amd/xdna-driver/pull/35
