### ISSUE TITLE
Guidance please?

### ISSUE THREAD

**Issue by hrstoyanov** [amd/xdna-driver#38]
Can you please share the roadmap for this project. I which Linux kernel can this driver be found, without messing around with custom builds?

I have a Ryzen 7940hs system that I still cannot use on Linux fully, because it is not officially supported by AMD.

**Comment by maxzhen** [comment]
The main reason we need customized kernel is for the IOMMU patch sets that our driver is depending on. The patch may land in 6.10. So, once the IOMMU feature is fully upstreamed, we can switch to standard Linux kernel for the driver.

**Comment by maxzhen** [comment]
Yes. We have updated our README to require 6.10 already.

**Comment by maxzhen** [comment]
> Thank you @maxzhen ! So, this means that soon for any 6.10+ systems I do not have to build th driver, just use it and it is standard part of the Linux kernel?

The dependency has been met in 6.10. The driver itself has not been upstreamed. We have sent out the patch set to Linux kernel community for review. It will take some time before it can be merged to the Linux kernel. Stay tuned, please.
