### ISSUE TITLE
How about integration with Pytorch?

### ISSUE THREAD

**Issue by serhii-nakon** [amd/xdna-driver#5]
I think that integration with Pytorch can trigger most consumers to buy those laptops just to start working with AI. 
Also it can be opponent to Macbooks that already use their iGPU for Pytorch tasks and it very popular usage case!!!

And need to remember that Ryzen has dedicated AI engine that more power efficient then Macbook's iGPU that a big pros!

**Comment by ntua-el19019** [comment]
I agree with that, It is not even a matter of choice anymore if you want to integrate local AI tasks such as LLMs. For example existing frameworks that allow you to run models even in you CPU efficiently, in the case of ollama, would greatly benefit from the acceleration of an NPU.

**Comment by maxzhen** [comment]
There will be other common software layers built upon the driver / XRT to do this.

**Comment by serhii-nakon** [comment]
Do you have some plans?

**Comment by serhii-nakon** [comment]
@maxzhen Do you have some plans?

**Comment by andyluo7** [comment]
@serhii-nakon , you can export from pytorch to onnx models and run it with Ryzen AI SW to leverage NPU in Ryzen AI laptops. For more info, please check - https://ryzenai.docs.amd.com/en/latest/

**Comment by serhii-nakon** [comment]
@andyluo7 I mean use NPU to accelerate ML, not only execution!
Like use it instead of GPU fully.

**Comment by andyluo7** [comment]
@serhii-nakon, you can use NPU to accelerate ML inference following https://ryzenai.docs.amd.com/en/latest/. NPU is not designed for ML training.

**Comment by nstiurca** [comment]
> @serhii-nakon , you can export from pytorch to onnx models and run it with Ryzen AI SW to leverage NPU in Ryzen AI laptops. For more info, please check - [ryzenai.docs.amd.com/en/latest](https://ryzenai.docs.amd.com/en/latest/)

Ryzen AI is for Windows 11, per its [installation instructions](https://ryzenai.docs.amd.com/en/latest/inst.html).

So I think the question remains how to use this _Linux_ driver for NPU acceleration of Pytorch in _Linux_?
