### ISSUE TITLE
How many memory does the Ryzen 7 8700g' s 780m can address ?

### ISSUE THREAD

**Issue by themoneyevo** [amd/xdna-driver#57]
If I have 256g memory on board, how many Gbit memory will be address by 780m ?

**Comment by maxzhen** [comment]
This driver is for the NPU device on Ryzen 7. It is not for the GPU one. We can't answer your question here.

**Comment by themoneyevo** [comment]
how many Gbit memory will be address by npu ?

**Comment by themoneyevo** [comment]
@keryell  So, base on the Noc, the AIE-ML Array can access the whole memory. Can we use the npu to accelerate training ?
