### ISSUE TITLE
Build XRT failed. Any depends on Vitis?

### ISSUE THREAD

**Issue by alexhegit** [amd/xdna-driver#68]
![image](https://github.com/amd/xdna-driver/assets/31022192/a632408f-2826-43cd-8b54-cf34679c8688)

Got issue 

![image](https://github.com/amd/xdna-driver/assets/31022192/f52b9a17-a6e7-4ad8-8374-ef7c3cb14c7c)

What dose it means? any depends on Vitis?

**Comment by maxzhen** [comment]
You can ignore this warning message. I do not see other cmake output from your log. I'm assuming they work for you.

**Comment by keryell** [comment]
Perhaps there are some missing requirements which are not available on your system?
Like `sudo xrt/src/runtime_src/tools/scripts/xrtdeps.sh` mentioned in https://xilinx.github.io/XRT/master/html/build.html ?

**Comment by mamin506** [comment]
> Perhaps there are some missing requirements which are not available on your system? Like `sudo xrt/src/runtime_src/tools/scripts/xrtdeps.sh` mentioned in https://xilinx.github.io/XRT/master/html/build.html ?

In this repo's readme, see https://github.com/amd/xdna-driver?tab=readme-ov-file#prerequisite
User should run amdxdna_deps.sh with root privilege. Under the hood, it will run xrtdeps.sh you mentioned.

The xdna-driver doesn't depend on Vitis tool.
In this case, XRT submodule is warning people that it will NOT build some MicroBlaze firmware. The Ryzen AI doesn't require those binaries. As Max said, please ignore these warning.

This warning doesn't lead to XRT build failed. If XRT build failed, we will need full build log to tell why.

**Comment by antheas** [comment]
Seems like you need to run build in XRT like this:
`./build.sh -noert`

As the error says. Not that the build worked... But at the same time I am not on Ubuntu.

**Comment by maxzhen** [comment]
> Seems like you need to run build in XRT like this: `./build.sh -noert`
> 
> As the error says. Not that the build worked... But at the same time I am not on Ubuntu.

You can do build with '-noert', but that does not matter, as we have suggested above. Please provide full build log for us to see why it fail. Ubuntu might be a key requirement here, yes.

**Comment by antheas** [comment]
I rebuilt in Ubuntu to try it and it worked.

Without using the -noert option, it just displays the error and exits. I also had to do it in Ubuntu. Maybe it changed in a recent version.

I would consider updating the build instructions.

**Comment by maxzhen** [comment]
Done: https://github.com/amd/xdna-driver/pull/132
